on:
  push:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm init -y
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v3
        with:
          extensions: 'js'
          annotations: true
